site_name: FLIMari Docs
nav:
  - Home: index.md
  - User Guide:
    - Tutorials: user-guide/tutorials.md
    - API Documentation: user-guide/api.md
  - About: about.md
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.blocks.caption
  - toc:
      permalink: "#"